config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reviews#index'
  resources :reviews do
    post 'add' => 'like_reviews#create'
    delete '/add' => 'like_reviews#destroy'
    resources :comments, only: [:create, :destroy] do
      post 'add' => 'like_comments#create'
      delete '/add' => 'like_comments#destroy'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  resources :categories, only: [:index, :new, :create, :show]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_reviews
  has_many :reviews, through: :category_reviews

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories1 = Category.where(group_id: 0)
    @categories3 = Category.where(group_id: 2)
    @categories4 = Category.where(group_id: 3)
    # @maker1=日本メーカー
    @maker1 = Category.where(group_id: 11)
    @maker2 = Category.where(group_id: 12)
    @maker3 = Category.where(group_id: 13)
    @maker4 = Category.where(group_id: 14)
  end
  
  def new
    @category = Category.new
  end

  def create
    # @group = Group.new(group_params)
  end

  def show
    @category = Category.find(params[:id])
    @reviews = Review.joins(:category_reviews).where({category_reviews: {category_id: [@category.id]}}).order("updated_at DESC")
    # カテゴリーidが一致するレビューを全て取得
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/views/categories/index.html.haml
= render "reviews/header"
.categoryIndex
  .category__box
    %p 見たいカテゴリーを選択してください
    .top__box
      .box1
        %p 国
        %a.icon1{"data-target" => "category_list1"}
          =icon("fas","comment-dots")
        #category_list1
          .form
            - @categories1.each do |cat1|
              .cate__name
                = link_to cat1.name, category_path(cat1.id), class: :category__name
      .box2
        %p メーカー
        %a.icon1{"data-target" => "category_list2"}
          =icon("fas","comment-dots")
        #category_list2
          .japan-box
            %p 日本
            %a.icon1{"data-target" => "category_list11"}
              =icon("fas","comment-dots")
              #category_list11
                .form
                  - @maker1.each do |mak1|
                    .cate__name
                      = link_to mak1.name, category_path(mak1.id), class: :category__name
          .europe-box
            %p 欧州
            %a.icon1{"data-target" => "category_list12"}
              =icon("fas","comment-dots")
              #category_list12
                .form
                  - @maker2.each do |mak2|
                    .cate__name
                      = link_to mak2.name, category_path(mak2.id), class: :category__name
          .noth_america-box
            %p 北米
            %a.icon1{"data-target" => "category_list13"}
              =icon("fas","comment-dots")
              #category_list13
                .form
                  - @maker3.each do |mak3|
                    .cate__name
                      = link_to mak3.name, category_path(mak3.id), class: :category__name
          .other-box
            %p その他メーカー
            %a.icon1{"data-target" => "category_list14"}
              =icon("fas","comment-dots")
              #category_list14
                .form
                  - @maker4.each do |mak4|
                    .cate__name
                      = link_to mak4.name, category_path(mak4.id), class: :category__name

    .bottom__box
      .box3
        %p type
        %a.icon1{"data-target" => "category_list3"}
          =icon("fas","comment-dots")
        #category_list3
          .form
            - @categories3.each do |cat3|
              .cate__name
                = link_to cat3.name, category_path(cat3.id), class: :category__name
      .box4
        %p その他
        %a.icon1{"data-target" => "category_list4"}
          =icon("fas","comment-dots")
        #category_list4
          .form
            - @categories4.each do |cat4|
              .cate__name
                = link_to cat4.name, category_path(cat4.id), class: :category__name
= render "reviews/footer"

app/views/categories/show.html.haml
-# カテゴリー
-# = @category.name
-# のショー
-# - @reviews.each do |review|
-#   = review.title
= render "reviews/header"
.categoryShow
  .title-box
    カテゴリー
    - if @category.group_id == 0
      国名：「
    - elsif @category.group_id == 11 or @category.group_id == 12 or @category.group_id == 13 or@category.group_id == 14
      メーカー：「
    - elsif @category.group_id == 2
      type：「
    - elsif @category.group_id == 3
      その他：「
    -else 
      error
    %span
      = @category.name
    」の投稿
  .search-box
    .search__results--box
      - @reviews.each do |review|
        .result
          .result__image
            .resul__image--box
              = link_to (image_tag review.image.url, height: '135px', width: '240px', class: 'test' if review.image.present?), review_path(review.id)
          .result__text
            .result__text--title
              = link_to truncate(review.title, length: 13), review_path(review.id), class: :title
            .result__text--main
              = truncate(review.text, length: 200)
              .show_link-box
                = link_to "続きはここをクリック", review_path(review.id), class: :show_link
            .result__text--date
              = review.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[review.created_at.wday]})")


= render "reviews/footer"