config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reviews#index'
  resources :reviews do
    post 'add' => 'like_reviews#create'
    delete '/add' => 'like_reviews#destroy'
    resources :comments, only: [:create, :destroy] do
      post 'add' => 'like_comments#create'
      delete '/add' => 'like_comments#destroy'
    end
    collection do
      get 'search'
    end
  end
  resources :users, only: :show 
  resources :categories, only: [:index, :new, :create, :show]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :like_reviews, dependent: :destroy
  has_many :users, through: :like_reviews

  has_many :category_reviews, dependent: :destroy
  has_many :categories, through: :category_reviews

  validates :title, presence: true, length: { maximum: 60 }
  validates :image, presence: true
  validates :text, presence: true

  mount_uploader :image, ImageUploader
  
  def self.search(search)
    if search
      Review.where('title LIKE(?)', "%#{search}%")
    else
      Review.all
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :back_index, only: [:new, :edit, :destroy, :create, :update]

  def index
    @reviews = Review.all.order("updated_at DESC").limit(40)
    @sidereviews = Review.order("updated_at ASC").limit(5)
  end

  def new
    @review = Review.new
    @category1 = Category.where(group_id: 0)
    @category3 = Category.where(group_id: 2)
    @category4 = Category.where(group_id: 3)

    @maker1 = Category.where(group_id: 11)
    @maker2 = Category.where(group_id: 12)
    @maker3 = Category.where(group_id: 13)
    @maker4 = Category.where(group_id: 14)
  end

  def create
    review = Review.create(review_params)
    if review.save
      redirect_to root_path, notice: '投稿が完了しました'
    else
      flash[:notice] = '投稿が失敗しました'
      redirect_to new_review_path
    end
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
    @comments = @review.comments.includes(:user).order("created_at DESC")
    @like_reviews = LikeReview.where(review_id: [@review.id])
    @like_review_count = @like_reviews.count
    cattag = Category.joins(:category_reviews).where({category_reviews: {review_id: [@review.id]}})
    # このレビューに付与されているカテゴリーを全て取得
    @tag1 = cattag.find_by(group_id: 0)
    @tag3 = cattag.find_by(group_id: 2)
    @tag4 = cattag.find_by(group_id: 3)

    @maker1 = cattag.find_by(group_id: 11)
    @maker2 = cattag.find_by(group_id: 12)
    @maker3 = cattag.find_by(group_id: 13)
    @maker4 = cattag.find_by(group_id: 14)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy
    flash[:notice] = '投稿を削除しました'
    redirect_to root_path
  end

  def edit
    @review = Review.find(params[:id])
    @category1 = Category.where(group_id: 0)
    @category3 = Category.where(group_id: 2)
    @category4 = Category.where(group_id: 3)

    @maker1 = Category.where(group_id: 11)
    @maker2 = Category.where(group_id: 12)
    @maker3 = Category.where(group_id: 13)
    @maker4 = Category.where(group_id: 14)
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    if review.save
      redirect_to review_path, notice: '編集が完了しました'
    else
      flash[:notice] = '編集が失敗しました'
      redirect_to edit_review_path
    end
  end

  def search
    @reviews = Review.search(params[:keyword])
    @sidereviews = Review.order("updated_at ASC").limit(5)
  end

  private
  def review_params
    params.require(:review).permit(:title, :text, :image, category_ids: []).merge(user_id: current_user.id)
  end

  def back_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_with_hashtags(content)
    content.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
  end 
end

app/views/reviews/_footer.html.haml
.footer
  .tweet--btn
    = link_to "https://twitter.com/share?text=car_reviewサイトを閲覧中！！&url=https://car-review-yoshizawa.herokuapp.com", :onclick => "window.open(encodeURI(decodeURI(this.href)), 'tweetwindow', 'width=650, height=470, personalbar=0, toolbar=0, scrollbars=1, sizable=1'); return false;", :rel => "nofollow" do
      .tweet--btn__box
        %i.fab.fa-twitter
  

app/views/reviews/_header.html.haml
.header
  .header__container
    - if user_signed_in?
      .user-fix
        -# = link_to truncate(current_user.name, length: 13), root_path, class: :user_name
        = link_to "ユーザー：#{truncate(current_user.name, length: 13)}", "/users/#{current_user.id}", class: :user_name

    -else
      .header-fix3
    .title
      = link_to "car Reviews", root_path, class: :title__name
    .header-fix1
      - if user_signed_in?
        .header-fix2
        .logout__btn
          = link_to "LOGOUT", destroy_user_session_path, method: :delete, class: :logout
      - else
        .user__name--fix2
        .login__btn
          = link_to "LOGIN", new_user_session_path, class: :login
  .menu-bar
    - if user_signed_in?
      .my_link-btn
        = link_to "/users/#{current_user.id}", class: :my_link do
          マイページ
      .show_link-btn
        = link_to root_path, class: :show_link do
          最新投稿
      .post-btn
        = link_to new_review_path, class: :post do
          投稿する
      .likes-btn
        = link_to categories_path, class: :likes do
          カテゴリー
    - else
      .header-fix4
      .new-btn
        = link_to new_user_registration_path, class: :new do
          新規登録
  = render 'layouts/notifications'

app/views/reviews/create.html.haml
投稿が完了しました。
= link_to root_path, class: :a do
  トップへ戻る

app/views/reviews/edit.html.haml
= render "header"
.newmain
  .newmain__form
    = form_with model: @review, local: true, class: 'form' do |form| 
      %h3
        編集する
        %span
          (画像は16:9)
      .main__form--title
        = form.text_field :title, placeholder: "title", class: 'title'
      .main__form--image
        = form.label :image do
          = icon('fas', 'image')
        = form.file_field :image, placeholder: "画像を選択 16:9", class: 'image'
      .main__form--text
        = form.text_area :text, placeholder: "text" , rows: "10", class: 'text' 
      .check
        %p カテゴリーを設定してください(それぞれ1つずつ・任意)
        .group_top
          .group_1
            %p 国
            %a.icon1{"data-target" => "category_list1"}
              =icon("fas","comment-dots")
            #category_list1
              .form
                = form.collection_check_boxes :category_ids, @category1, :id, :name


          .group_2
            %p メーカー
            %a.icon2{"data-target" => "category_list2"}
              =icon("fas","comment-dots")
            #category_list2
              .japan-box
                %p 日本
                %a.icon2{"data-target" => "category_list11"}
                  =icon("fas","comment-dots")
                #category_list11
                  .form
                    = form.collection_check_boxes :category_ids, @maker1, :id, :name
              .europe-box
                %p 欧州
                %a.icon2{"data-target" => "category_list12"}
                  =icon("fas","comment-dots")
                #category_list12
                  .form
                    = form.collection_check_boxes :category_ids, @maker2, :id, :name
              .north_america-box
                %p 北米
                %a.icon2{"data-target" => "category_list13"}
                  =icon("fas","comment-dots")
                #category_list13
                  .form
                    = form.collection_check_boxes :category_ids, @maker3, :id, :name
              .other-box
                %p その他
                %a.icon2{"data-target" => "category_list14"}
                  =icon("fas","comment-dots")
                #category_list14
                  .form
                    = form.collection_check_boxes :category_ids, @maker4, :id, :name

          .group_3
            %p タイプ
            %a.icon3{"data-target" => "category_list3"}
              =icon("fas","comment-dots")
            #category_list3
              .form
                = form.collection_check_boxes :category_ids, @category3, :id, :name
          .group_4
            %p その他
            %a.icon4{"data-target" => "category_list4"}
              =icon("fas","comment-dots")
            #category_list4
              .form
                = form.collection_check_boxes :category_ids, @category4, :id, :name
      .main__form--send
        = form.submit "SEND", class: 'send'
= render "footer"

app/views/reviews/hashtag.html.haml
- provide(:title, @tag.hashname)
.row
  .col-md-9
    .block1_hash
      -# = image_tag("hashtag.png")
      .block2_hash
        .name_hash
          = @tag.hashname
        .edit_hash
          = render 'users/follow_form'
        .fllw_hash
          = render 'shared/user_info_default'
          %span{:style => "margin-right:15px;"}
          = render 'shared/stats_default'
.row
  .posted_content
    .col-md-8
      .picture_hash
        = render @micropost
      / .picture

app/views/reviews/index.html.haml
= render "header"
.main
  .main__container
    .main__container--left
      .search-box 
        = form_with url: search_reviews_path, method: :get, local: true do |form|
          = form.text_field :keyword, placeholder: "投稿を検索する", class: 'form'
          = form.submit "検索", class: 'btn'
          
      .search__results--box
        - @reviews.each do |review|
          .result
            .result__image
              .resul__image--box
                = link_to (image_tag review.image.url, height: '135px', width: '240px', class: 'test' if review.image.present?), review_path(review.id)
            .result__text
              .result__text--title
                = link_to truncate(review.title, length: 13), review_path(review.id), class: :title
              .result__text--main
                = truncate(review.text, length: 90)
                .show_link-box
                  = link_to "続きはここをクリック", review_path(review.id), class: :show_link
              .result__text--date
                = review.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[review.created_at.wday]})")

    .main__container--right
      .random-box
        %p おすすめの投稿
        - @sidereviews.each do |saide|
          = link_to (image_tag saide.image.url, height: '90px', width: '160px', class: 'test' if saide.image.present?), review_path(saide.id) 
= render "footer"

app/views/reviews/new.html.haml
= render "header"
.newmain
  .newmain__form
    = form_with model: @review, local: true, class: 'form' do |form| 
      %h3
        投稿する
        %span
          (画像は16:9)
      .main__form--title
        = form.text_field :title, placeholder: "title", class: 'title'
      .main__form--image
        = form.label :image do
          = icon('fas', 'image')
        = form.file_field :image, placeholder: "画像を選択 16:9", class: 'image'
      .main__form--text
        = form.text_area :text, placeholder: "text" , rows: "10", class: 'text' 
      .check
        %p カテゴリーを設定してください(それぞれ1つずつ・任意)
        .group_top
          .group_1
            %p 国
            %a.icon1{"data-target" => "category_list1"}
              =icon("fas","comment-dots")
            #category_list1
              .form
                = form.collection_check_boxes :category_ids, @category1, :id, :name


          .group_2
            %p メーカー
            %a.icon2{"data-target" => "category_list2"}
              =icon("fas","comment-dots")
            #category_list2
              .japan-box
                %p 日本
                %a.icon2{"data-target" => "category_list11"}
                  =icon("fas","comment-dots")
                #category_list11
                  .form
                    = form.collection_check_boxes :category_ids, @maker1, :id, :name
              .europe-box
                %p 欧州
                %a.icon2{"data-target" => "category_list12"}
                  =icon("fas","comment-dots")
                #category_list12
                  .form
                    = form.collection_check_boxes :category_ids, @maker2, :id, :name
              .north_america-box
                %p 北米
                %a.icon2{"data-target" => "category_list13"}
                  =icon("fas","comment-dots")
                #category_list13
                  .form
                    = form.collection_check_boxes :category_ids, @maker3, :id, :name
              .other-box
                %p その他
                %a.icon2{"data-target" => "category_list14"}
                  =icon("fas","comment-dots")
                #category_list14
                  .form
                    = form.collection_check_boxes :category_ids, @maker4, :id, :name

          .group_3
            %p タイプ
            %a.icon3{"data-target" => "category_list3"}
              =icon("fas","comment-dots")
            #category_list3
              .form
                = form.collection_check_boxes :category_ids, @category3, :id, :name
          .group_4
            %p その他
            %a.icon4{"data-target" => "category_list4"}
              =icon("fas","comment-dots")
            #category_list4
              .form
                = form.collection_check_boxes :category_ids, @category4, :id, :name
      .main__form--send
        = form.submit "SEND", class: 'send'
= render "footer"

app/views/reviews/search.html.haml
= render "header"
.main
  .main__container
    .main__container--left
      .search-box 
        = form_with url: search_reviews_path, method: :get, local: true do |form|
          = form.text_field :keyword, placeholder: "投稿を検索する", class: 'form'
          = form.submit "検索", class: 'btn'
          
      .search__results--box
        - @reviews.each do |review|
          .result
            .result__image
              .resul__image--box
                = link_to (image_tag review.image.url, height: '135px', width: '240px', class: 'test' if review.image.present?), review_path(review.id)
            .result__text
              .result__text--title
                = link_to truncate(review.title, length: 13), review_path(review.id), class: :title
              .result__text--main
                = truncate(review.text, length: 90)
                .show_link-box
                  = link_to "続きはここをクリック", review_path(review.id), class: :show_link
              .result__text--date
                = review.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[review.created_at.wday]})")

    .main__container--right
      .random-box
        %p おすすめの投稿
        - @sidereviews.each do |saide|
          = link_to (image_tag saide.image.url, height: '90px', width: '160px', class: 'test' if saide.image.present?), review_path(saide.id) 
= render "footer"

app/views/reviews/show.html.haml
= render "header"
.showTop
  .top-container
    .top__picture
      .top__picture--image
        = image_tag @review.image.url, height: '270px', width: '480px', class: 'image' if @review.image.present?
    .top__items
      .tag
        - if @tag1
          .tag-list
            .tag-list_name
              = link_to @tag1.name, category_path(@tag1.id),class: :tag__name
        - if @maker1 or @maker2 or @maker3 or @maker4
          .tag-list
            .tag-list_name
              - if @maker1
                = link_to @maker1.name, category_path(@maker1.id),class: :tag__name
              - if @maker2
                = link_to @maker2.name, category_path(@maker2.id),class: :tag__name
              - if @maker3
                = link_to @maker3.name, category_path(@maker3.id),class: :tag__name
              - if @maker4
                = link_to @maker4.name, category_path(@maker4.id),class: :tag__name
        - if @tag3
          .tag-list
            .tag-list_name
              = link_to @tag3.name, category_path(@tag3.id),class: :tag__name
        -if @tag4
          .tag-list
            .tag-list_name
              = link_to @tag4.name, category_path(@tag4.id),class: :tag__name
        .like-count
          %span
            お気に入り
          .counter
            %i.fas.fa-star
            x
            = @like_review_count
      .top__items--title
        .title__name
          = @review.title
        .title__user
          投稿者：
          = link_to truncate(@review.user.name, length: 20), "/users/#{@review.user_id}",class: :reviewer
      .top__items--btn
        - if user_signed_in? && @review.user_id == current_user.id
          .edit-btn
            = link_to "編集", edit_review_path, class: :edit
          .delete-btn
            = link_to "削除", review_path, method: :delete, class: :delete
        -elsif user_signed_in? && @review.user_id != current_user.id
          .like-btn
            -# = link_to "お気に入り", edit_review_path, class: :like
            - if !LikeReview.exists?(user_id: current_user.id, review_id: @review.id)
              = link_to "お気に入り",review_add_path(@review),method: :post, class: :like 
            - else
              = link_to "お気に入り解除",review_add_path(@review),method: :delete, class: :like
        - else user_signed_in?
          .login-btn
            = link_to "お気に入り登録をするにはログインしてください", new_user_session_path, class: :login
.showMain
  .review
    .review__text 
      = simple_format @review.text
.showBottom
  .showBottom__title
    この投稿へのコメント
  .bottom__comment--form
    - if current_user
      = form_with(model: [@review, @comment], local: true, id: "new_comment") do |form|
        .form__container
          .form
            = form.text_field :text, placeholder: "コメントする", row: 2, class: :textbox
          .send-btn
            = form.submit "投稿", class: :submit
    - else
      = link_to "コメントを投稿するにはログインしてください", new_user_session_path, class: :login
  .bottom__comment--list
    .comment__title
      ＜コメント一覧＞
    .comment__list
      - if @comments
        - @comments.each do |comment| 


          .comment__list--box
            .user-name
              = link_to truncate(comment.user.name, length: 20), "/users/#{comment.user_id}" 
            .date
              = comment.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[comment.created_at.wday]})")
          .comment__list--bottom
            .comment
              = comment.text 
            .delete__btn
              -# %a{:href => "#"} 削除
            .fav
            -# = link_to "星", review_comment_add_path(@review, @comment), method: :post

            
= render "footer"